// <auto-generated />
using AlcoPlus.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlcoPlus.API.Migrations
{
    [DbContext(typeof(AlcoPlusDbContext))]
    [Migration("20231105073625_SeededCountriesAndHotels")]
    partial class SeededCountriesAndHotels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlcoPlus.API.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Philippines",
                            ShortName = "PH"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Japan",
                            ShortName = "JP"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bahamas",
                            ShortName = "BH"
                        });
                });

            modelBuilder.Entity("AlcoPlus.API.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hotel address 1",
                            CountryId = 1,
                            Name = "Hotel 1",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hotel address 2",
                            CountryId = 1,
                            Name = "Hotel 2",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Hotel address 3",
                            CountryId = 2,
                            Name = "Hotel 3",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Hotel address 4",
                            CountryId = 1,
                            Name = "Hotel 4",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 5,
                            Address = "Hotel address 5",
                            CountryId = 3,
                            Name = "Hotel 5",
                            Rating = 2.5
                        });
                });

            modelBuilder.Entity("AlcoPlus.API.Entities.Hotel", b =>
                {
                    b.HasOne("AlcoPlus.API.Entities.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AlcoPlus.API.Entities.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
